blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'index.html', views.index, name="index"),
    url(r'projects.html', views.view_projects, name="projects"),
    url(r'blog_main.html', views.blog_main, name="blog_main"),
    url(r'about.html', views.about, name="about"),
    url(r'cat/(?P<slug>[^\.]+).html', views.view_category, name="category"),
    url(r'^(?P<slug>[^\.]+).html', views.view_post, name="post"),

]

shelbycodes/urls.py
from django.contrib import admin
from django.conf.urls import include, url

from blog import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'index.html', views.index),
    url(r'', include('blog.urls')),
    url(r'admin/', admin.site.urls),
]

blog/models.py
from __future__ import unicode_literals
from django.db import models
from django.urls import reverse
import datetime


class Category(models.Model):
    title = models.CharField(max_length=100, null=True, db_index=True)
    slug = models.SlugField(max_length=100, null=True, db_index=True)

    def __str__(self):
        return self.title

    def __unicode__(self):
        return '%s' % self.titleclear

    # def get_absolute_url(self):
    #     return reverse('view_blog_category', args=[self.slug])


class Post(models.Model):
    title = models.CharField(max_length=255, default='0000000')
    img = models.CharField(max_length=500, default="/static/images/default.jpg")
    body = models.TextField(default='0000000')
    slug = models.SlugField(max_length=100, default='0000000', db_index=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
    create_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    publish_date = models.DateTimeField(null=True)
    today = datetime.date.today()
    publish_month = today.month

    def __str__(self):
        return self.title

    def __unicode__(self):
        return '%s' % self.title

    # def get_absolute_url(self):
    #     return reverse('view_blog_post', args=[self.slug])

blog/views.py
# from blog.models import Post, Category
from django.shortcuts import get_object_or_404, render

from blog.models import Post, Category


def index(request):
    return render(request, 'blog/index.html', {
        'categories': Category.objects.all(),
        'posts': Post.objects.all()[:10],
    })


def view_post(request, slug):
    post = get_object_or_404(Post, slug=slug)
    return render(request, 'blog/post.html', {
        'categories': Category.objects.all(),
        'posts': Post.objects.all(),
        'post': post,
    })


def view_category(request, slug):
    category = get_object_or_404(Category, slug=slug)
    print("cat:", slug)
    return render(request, 'blog/category.html', {
        'category': category,
        'categories': Category.objects.all(),
        'posts': Post.objects.filter(category=category)
    })


def view_projects(request):
    return render(request, 'blog/projects.html', {
        'categories': Category.objects.all(),
        'posts': Post.objects.all(),
    })


def blog_main(request):
    return render(request, 'blog/blog_main.html', {
        'categories': Category.objects.all(),
        'posts': Post.objects.all(),
    })


def about(request):
    return render(request, 'blog/about.html', {
        'categories': Category.objects.all(),
        'posts': Post.objects.all(),
    })

blog/templates/blog/about.html
{% extends 'blog/index.html' %}

{% block content-title %}About{% endblock %}

{% block welcome %}{% endblock %}

{% block content %}

<p>I am a ghost!</p>

{% endblock %}

blog/templates/blog/blog_main.html
{% extends 'blog/index.html' %}

{% block content-title %}Blog{% endblock %}

{% block welcome %}{% endblock %}

{% block content %}

    <div id="post-sub-container">
        {% if posts %}
            {% for post in posts %}
                <div id="blog-post">
                    <img src="{{ post.img }}">
                    <p id="post-date-published">published: {{ post.publish_date }}</p>
                    <h3><a href="{% url 'blog:post' post.slug %}">{{ post.title }}</a></h3>
                    <p id="post-text">{{ post.body|truncatewords:30 }}</p>
                </div>
            {% endfor %}
            {% else %}
            <p>There are no posts.</p>
        {% endif %}
    </div>

{% endblock %}

blog/templates/blog/category.html
{% extends 'blog/index.html' %}
{% block content-title %}{{ category.title }}{% endblock %}

{% block welcome %}{% endblock %}

{% block content %}
    {% if posts %}
        <ul>
        {% for post in posts %}

            <li><a href="{% url 'blog:post' post.slug %}">{{ post.title }}</a></li>
        {% endfor %}
        </ul>
        {% else %}
        <p>There are no posts.</p>
    {% endif %}
{% endblock %}

blog/templates/blog/index.html
{% load static %}
{#{% load django_bootstrap_breadcrumbs %}#}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>{% block head_title %}shelby_codes{% endblock %}</title>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href="https://fonts.googleapis.com/css?family=Asap|Nunito+Sans|VT323" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">


</head>
<body>
<div id="body-container" class="container-fluid">
{##}
{#{% block breadcrumbs %}#}
{#    {% clear_breadcrumbs %}#}
{#    {% breadcrumb 'Categories' categories %}#}
{#{% endblock %}#}

    <div class="page-header">
        <h1 id="title"><a class="title" href="index.html">{% block title %}shelby_codes{% endblock %}</a></h1>
            <ul id="menu_list">
                <li class="menu"><a href="{% url 'blog:about' %}" class="menu">About</a></li>
                <li class="menu"><a href="{% url 'blog:projects' %}" class="menu">Projects</a></li>
                <li class="menu"><a href="{% url 'blog:blog_main' %}" class="menu">Blog</a></li>
                <li class="menu"><a href="{% url 'blog:index' %}" class="menu">Home</a></li>
            </ul>
    </div>

{# columns #}
    <div id="columns">
        <div id="sub-columns">

            {# START SIDE-MENU #}
            <div id="side-menu" class="menu container">

                    {% block sidemenu %}
                        <h2>Categories</h2>
                        <ul class="sidemenu">
                            {% for category in categories %}
                                <h4><a href="{% url 'blog:category' category.slug %}" id="cat_link">{{ category.title }}</a></h4>
                                {% for post in posts %}
                                    {% ifequal post.category category %}
                                    <li class="sidemenu"><a class="sidemenu" href="{% url 'blog:post' post.slug %}"><sup>|</sup>--{{ post.title|truncatechars:25 }}</a></li>
                                    {% endifequal %}
                                {% endfor %}

                            {% endfor %}
                        </ul>
                    {% endblock %}

            </div>
            {# END SIDE-MENU #}


            {# START BLOG-POSTS #}
            <div id="post-container" class="content container">
                <div id="breadcrumbs">Breadcrumbs > breadcrumbs</div>
                {% block welcome %}
                    <h1 id="welcome-title">Welcome!</h1>
                    <p class="welcome-content">
                        Updates:
                    </p>
                {% endblock welcome %}
                {% block content-title %}<h2 id="content-title">New Posts</h2>{% endblock %}

                {% block content %}

{#                {% render_breadcrumbs %}#}
                <div id="post-sub-container">
                {%  if posts %}
                    {% for post in posts reversed %}
                        <div id="blog-post">
                         <img src="{{ post.img }}">
                            <p id="post-date-published">published: {{ post.publish_date }}</p>
                            <h3><a href="{% url 'blog:post' post.slug %}">{{ post.title }}</a></h3>
                            <p id="post-text">{{ post.body|truncatewords:20 }}</p>
                        </div>
                    {% endfor %}
                    {% else %}
                    <p>There are no posts.</p>
                {% endif %}
                </div>
                {% endblock %}
            </div>
            {# END BLOG-POSTS#}


            {# START RIGHT-SIDE-BAR #}
            <div id="sidebar-container">
                {% block sidebar %}
                    <div id="sidebar-sub-container">
                    <h2>Archives</h2>
                        <ul class="archives-list">
                        <h4 class="archives-month">August 2018</h4>
                            {% for post in posts %}
                                {% ifequal post.publish_month 8 %}
                                    <li class="archives-list">
                                        <a class="archives-list" href="{% url 'blog:post' post.slug %}">{{ post.title }}</a>
                                    </li>
                                {% endifequal %}
                            {% endfor %}
                        </ul>
                    <h2>Keywords</h2>
                    </div>
                {% endblock sidebar %}
            </div>
            {# END RIGHT-SIDE-BAR #}
        </div>
    </div>
{# end columns #}



</div>


<div id="footer">
    {% block footer %}
    {% endblock %}
</div>
</body>
</html>

blog/templates/blog/post.html
{% extends 'blog/index.html' %}

{#{% load django_bootstrap_breadcrumbs %}#}
{#{% block head_title %}{{ post.title }}{% endblock %}#}
{% block content-title %}{% endblock %}
{% block welcome %}{% endblock %}
{#{% block breadcrumbs %}#}
{##}
{#    {{ block.super }}#}
{#    {% breadcrumb 'Post' url 'blog:post' post.slug %}#}
{#{% endblock %}#}

{% block content %}
 <div id="post-sub-container">
    <div id="blog-post">

        {# HEADER #}
        <div id="post-header">
            <h3 id="post-title">{{ post.title }}</h3>
            <h4 id="post-subline">{{ post.publish_date }} by Shelby</h4>
            <img id="post-img" src="{{ post.img }}">
        </div>
        {# END HEADER #}
        {% autoescape off %}
        <p>{{ post.body }}</p>
        {% endautoescape %}
        </div>
    </div>
{% endblock %}

blog/templates/blog/projects.html
{% extends 'blog/index.html' %}

{% block content-title %}Projects{% endblock %}

{% block welcome %}{% endblock %}

{% block content %}

{% endblock %}